### ISSUE TITLE
PromDapterSvc Fails with Event ID 13 and 0 Errors in EventViewer

### ISSUE THREAD

**Issue by remiscarlet** [kallex/PromDapter#10]
Hi there, love the work that's been done here.

I have a bit of a headscratcher here. I managed to set up PromDapter great just yesterday and had the whole pipeline from PromDapter->Prometheus->Grafana working great. This morning when I woke up, I noticed that the graphs had stopped overnight for this same host. Host is powered on 24/7. 

Checking the EventViewer logs I'm seeing three entries every time, presumably, PromDapter attempts to start/restart. Two are errors and one is a warning. Apologies if you prefer the "Details" view - Two of the three issues have seemingly malformed XML so the "Details" tab is pretty messy to paste. I'm also not too familiar with EventViewer myself.

```
The description for Event ID 0 from source PromDapterSvc cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Category: PromDapterSvc.Controllers.MetricsController
EventId: 0
ConnectionId: 0HM94BGQCUO6Q
RequestId: 0HM94BGQCUO6Q:00000001
RequestPath: /metrics
SpanId: |db936f9a-401399c0aee1e160.
TraceId: db936f9a-401399c0aee1e160
ParentId: 
ActionId: 71ee9fdc-113f-4977-a1d7-a68c475a5986
ActionName: PromDapterSvc.Controllers.MetricsController.Get (PromDapterSvc)

No prefix defined in configuration; defaulting to hwi_


The message resource is present but the message was not found in the message table
```

```
The description for Event ID 0 from source PromDapterSvc cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Category: PromDapterSvc.Controllers.MetricsController
EventId: 0
ConnectionId: 0HM94BGQCUO6Q
RequestId: 0HM94BGQCUO6Q:00000001
RequestPath: /metrics
SpanId: |db936f9a-401399c0aee1e160.
TraceId: db936f9a-401399c0aee1e160
ParentId: 
ActionId: 71ee9fdc-113f-4977-a1d7-a68c475a5986
ActionName: PromDapterSvc.Controllers.MetricsController.Get (PromDapterSvc)

Unhandled error

Exception: 
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenCore(String mapName, HandleInheritability inheritability, Int32 desiredAccessRights, Boolean createOrOpen)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenCore(String mapName, HandleInheritability inheritability, MemoryMappedFileRights rights, Boolean createOrOpen)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenExisting(String mapName, MemoryMappedFileRights desiredAccessRights, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenExisting(String mapName, MemoryMappedFileRights desiredAccessRights)
   at SensorMonHTTP.HWiNFOProvider..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PrometheusProcessor.ServiceProcessor...MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PromDapterSvc.Controllers.MetricsController..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PromDapterSvc.Controllers.MetricsController..MoveNext()


The message resource is present but the message was not found in the message table
```

```
Category: Microsoft.AspNetCore.Server.Kestrel
EventId: 13
ConnectionId: 0HM94BGQCUO6Q
RequestId: 0HM94BGQCUO6Q:00000001
RequestPath: /metrics
SpanId: |db936f9a-401399c0aee1e160.
TraceId: db936f9a-401399c0aee1e160
ParentId: 

Connection id "0HM94BGQCUO6Q", Request id "0HM94BGQCUO6Q:00000001": An unhandled exception was thrown by the application.

Exception: 
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenCore(String mapName, HandleInheritability inheritability, Int32 desiredAccessRights, Boolean createOrOpen)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenCore(String mapName, HandleInheritability inheritability, MemoryMappedFileRights rights, Boolean createOrOpen)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenExisting(String mapName, MemoryMappedFileRights desiredAccessRights, HandleInheritability inheritability)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.OpenExisting(String mapName, MemoryMappedFileRights desiredAccessRights)
   at SensorMonHTTP.HWiNFOProvider..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PrometheusProcessor.ServiceProcessor...MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PromDapterSvc.Controllers.MetricsController..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PromDapterSvc.Controllers.MetricsController..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Interestingly, I also saw a different error earlier which does not seem to consistently show up, but indicates a specific filepath with `Could not find file C:\Windows\system32\Prometheusmapping.yaml`  which I thought was odd as the documentation only mentions `C:\ProgramData` and `C:\Program Files`. Not 100% sure how case sensitivity works with Windows applications but fwiw I did try adding my working copy of `Prometheusmapping.yaml` to that folder and did not manage to resolve the issue.

To try and amend the issue I have tried restarting my host multiple times, repairing the installation, as well as uninstalling then reinstalling. I also attempted to give blanket read/execute rights to the `C:/ProgramData/PromDapter` and `C:\Program Files/PromDapter` folders in case it was a file permission issue but that didn't seem to resolve anything. I did not try changing file permissions on `system32`.

Thanks again for working on this adapter and please let me know any other information I can provide!

**Comment by kallex** [comment]
The error comes from HWiNFO Shared Memory not being available, which requires the option to be enabled and sensors window opened (can be afterwards minimized). 

If there wasn't any restarts of HWiNFO, I'll take educated guess that the HWiNFO is v7.xx+ and it has introduced the 12 hour limit of Shared Memory feature for non-licensed free versions. You can try to confirm if that option is indeed become not-enabled and if re-enabling it solves the issue.

If that's the case, you can either downgrade to v6.20 (or something, I forget which exact version is the latest before the 12 hr time limit, or purchase the license for HWiNFO to keep it enabled.

Note: I'm in no way affiliated with HWiNFO licensing, but I understand and the reasoning behind it and support the cause.

**Comment by remiscarlet** [comment]
Wow, really appreciate the super fast response. That would absolutely explain why PromDapter stopped exporting metrics overnight. Still fairly new to HWInfo as well so didn't realize persistent memory-sharing was a feature locked behind a license.

I've purchased a license and everything is working great again! (I was planning on setting PromDapter up on a few more hosts in my home network anyway :))

Thanks so much and have a great day!
